FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o consumer .

FROM debian:stable-slim
WORKDIR /app
COPY --from=builder /app/consumer .

CMD ["./consumer"]



FROM golang:1.23-alpine

WORKDIR /app
COPY . .

RUN go mod init publisher && go get github.com/streadway/amqp && go get github.com/joho/godotenv && go build -o publisher .

CMD ["./publisher"]
