FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o consumer .

FROM debian:stable-slim
WORKDIR /app
COPY --from=builder /app/consumer .

CMD ["./consumer"]
